### ISSUE TITLE
Recommend a branching model

### ISSUE THREAD

**Issue by s-laugh** [esdc-devcop/esdc-devcop.github.io#10]
### Goals / Recommendation

Use GitFlow when starting a branching model with Git.
https://datasift.github.io/gitflow/IntroducingGitFlow.html 

Recommendation details are documented here, with some extra parts for committing/merging code that will assist in using this branching model.
https://esdc-devcop.github.io/guides/source-control/working-with-git.html

### Thoughts:  

* Those that know branching models and modern development practices probably won't like GitFlow as it's too much maintenance.
* GitFlow is similar to current TFS branching model used in ESDC, creating an easier transition.

### Plan:

- Focus on teaching, and demos
  - Why we need a branching model
  - Standard life-cycle deployment
  - Emergency release
  - Feature development
  - Reassurance of existing TFVC (TFS) standards
- Hands-on:
  - Set up branches
  - Configure settings
  - Walk though simplified change

**Comment by pabrams** [comment]
I like how [MS release flow](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow) doesn't have a dev branch and uses master as the working branch, but I think they can get away with that because they use feature flags.

**Comment by s-laugh** [comment]
> I like how [Microsoft's Release Flow](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow) doesn't have a dev branch and uses master as the working branch, but I think they can get away with that because they use feature flags.

There are a lot of different`t flows out there. with our development we don`t use GitFlow exactly but we take from a lot of the key points and work with a flow that works for our team and deployment cycles. Ultimately we will suggest the same for every team. 

GitFlow was picked because it is very similar to how we have been doing development in ESDC for many years, and provides a very well defined and described process to follow that still allows for customization depending on the project.
