### ISSUE TITLE
Bug: Expand/Close does not work on Details items listed with IE/Edge

### ISSUE THREAD

**Issue by lafeeflushette** [esdc-devcop/esdc-devcop.github.io#114]
**https://esdc-devcop.github.io/tools.html**

### Problem

The expand/close feature on items listed on screen does work in Firefox but it is not possible to expand/close items in IE11 and Edge.

### Expected Result

Same as in Firefox:

- Expand details on click
- Close details on click

**Comment by s-laugh** [comment]
I did notice the issue in IE, thanks for reporting.
The documentation for the control is here https://wet-boew.github.io/v4.0-ci/demos/details/details-en.html, will need more investigation.

**Comment by s-laugh** [comment]
Change in #120 did not fix the issue.

**Comment by s-laugh** [comment]
Looks like the JS in WET isn't being triggered to supplement the default HTML5 control, needed in IE and EDGE. There is a js file in CDTS that is being blocked, might be the file needed.
