### ISSUE TITLE
Topic: Automate A11y Testing / CCP-D Tech Stack

### ISSUE THREAD

**Issue by s-laugh** [esdc-devcop/esdc-devcop.github.io#117]
### Goals / Recommendation

Showcase tools and scripts used to automate a11y (accessibility) testing. 

Demonstrate how tools can be used to speed up delivery time and what can be done today to start using these tools on all of our applications today, even the legacy stuff.

As the a11y testing is actually quite short, a walk-though of the CCP-D Tech Stack will be shown as well.

_Would relate/cover the ideas from topics #85 #8_

### Community Expectations

* Knows a11y is important
* Knows some of the basic rules of a11y
* Is only doing manual a11y testing though the a11y group

### References

https://github.com/esdc-devx/auto-a11y-demo

**Comment by s-laugh** [comment]
fyi @CalvinRodo

**Comment by joel-ld** [comment]
I took the accessibility training by ESDC 2 weeks ago. They provide us a lot of useful tools and advice. It might be great.

**Comment by s-laugh** [comment]
> I took the accessibility training by ESDC 2 weeks ago. They provide us a lot of useful tools and advice. It might be great to involve their team.
This would probably be taking a bit of a diffren't approach, showing how tools are currently being used on systems we're building in ESDC.
