### ISSUE TITLE
Bug:  Artifactory recommendation is out-of-date

### ISSUE THREAD

**Issue by pabrams** [esdc-devcop/esdc-devcop.github.io#146]
**What page is the issue on:**
https://esdc-devcop.github.io/recommendations/artifactory.html

### Problem

We can't use artifactory anymore due to "licensing issues" (I don't know the details of what happened to the procurement)

### Expected Result

Delete section, or make new recommendation.  Not sure whether the on-prem ADO artifacts can provide a full replacement, but some teams have been using it, especially when there are proxy issues getting to nuget.org

**Comment by jeanbenoitrochon** [comment]
Sorry for late reply. We will document updated procedure shortly.

**Comment by jeanbenoitrochon** [comment]
Documentation for [Artifactory](https://esdc-devcop.github.io/recommendations/artifactory.html) and other related URL's have been edited to reflect current situation. Also, we added a Nuget section. in the "Asset management" Section of our [tools](https://esdc-devcop.github.io/tools.html) page.
