### ISSUE TITLE
Recommended tools - Programming languages

### ISSUE THREAD

**Issue by matherrien92** [esdc-devcop/esdc-devcop.github.io#206]
Currently the only recommended language we have is typescript.

https://dialogue/grp/CO7397744/TechStandardsLib/Development%20Languages.mht

We need to add the baseline languages. At least the main ones: C#, Java, VB.NET. We could also put a reference to the official documentation.

**Comment by j-paquette** [comment]
@matherrien92    
The baseline languages listed:   
* Java 
* Python 3.x 
* R (Programming Language) (AI) 
* Visual Basic .NET 
* C# (Part of Visual Studio.NET) 

Should we not include the older languages (ie, VB, R) in favour of the newer ones (ie, C#, Python)?    
Are there any languages missing?

**Comment by matherrien92** [comment]
I think we should include the languages the department is using the most. C#, VB.Net and JAVA. These would be the recommended ones.

**Comment by j-paquette** [comment]
Closing issue.
