### ISSUE TITLE
Managing Merge Requests - Using Code Review

### ISSUE THREAD

**Issue by s-laugh** [esdc-devcop/esdc-devcop.github.io#3]
### Goals / Recommendation

Describe **why** pull (merge) requests and code review are important.

Explain the use of Merge Requests, tracking the changes as code moves from branch to branch. Describing how to develop so merge requests are manageable.
Explain what it is that is being reviewed in a code review and how to do that effectively.

### Thoughts:  

* Code review has been tried before with poor tools and wasn't sustainable.

### Plan:

Demonstrate a code review.

### Related Issues

- esdc-devcop/presentations#25
- esdc-devcop/recommendations#10

**Comment by pabrams** [comment]
Is this issue for fleshing out the guidelines in the code review section of [Working With Git - Best Practices](https://github.com/esdc-devcop/strategy/blob/master/guides/working-with-git.md) or does it mean something else?

**Comment by s-laugh** [comment]
> 
> 
> Is this issue for fleshing out the guidelines in the [code review section of Working With Git - Best Practices](https://github.com/esdc-devcop/strategy/blob/master/guides/working-with-git.md#code-review) or does it mean something else?

The issue in particular is to have this as a topic for the DevCoP. But in order to present and give recommendations on how Code Review should work, it might also include fleshing out the guideline a bit more.

**Comment by s-laugh** [comment]
Presentation issue esdc-devcop/presentations#25
