### ISSUE TITLE
Determine Streams and OPIs

### ISSUE THREAD

**Issue by s-laugh** [esdc-devcop/esdc-devcop.github.io#38]
Need to confirm the streams and whole will be running the content for those streams.

**Streams**

* [ ] Micro-services - Interoperability
* [ ] CI/CD - _DTS?_
* [ ] Cloud - _Cloud CoE?_

**Comment by jeanbenoitrochon** [comment]
Offer our DevCoP platform to other teams 
SDS will be responsible for sending out invites, community engagement, boardroom reservation,  conf call and video setup & recordings: 
o	DTS: CI-CD ? -> Dwayne Moore
o	CCoE: Cloud -> Fahad Jawaid
o	Interop: API Store, managed API’s / Micro-service -> Michel Savoie

**Comment by jeanbenoitrochon** [comment]
Also send offering Patrick Heroux

**Comment by s-laugh** [comment]
> Also send offering Patrick Heroux

Patrick is going to be helping along with the rest of the CS04 is a more over-site capacity.

**Comment by s-laugh** [comment]
Can point the OPIs to our https://esdc-devcop.github.io/strategy/strategy.md#info-sessions (https://github.com/esdc-devcop/strategy/blob/strategy/strategy.md) details on what we hope sessions will look like.
