### ISSUE TITLE
Move Repo (name)

### ISSUE THREAD

**Issue by s-laugh** [esdc-devcop/esdc-devcop.github.io#48]
We need to update the name of the repo as the purpose has changed to be more a global space for hosting documents. The documents that are "published" are to be shown though GitHub Pages. In order to edit the header info on Pages, we have to change the name of the repo changing the location as well.

Using the name `esdc-devcop.github.io` will allow the root page to be at the address `https://esdc-devcop.github.io/`.

cc @Path125 @jeanbenoitrochon

**Comment by jeanbenoitrochon** [comment]
We can talk about it at monday's meeting. I agree we need to change the name, it won't take long to agree on one with the SA's. We'll fix the deadlinks afterwards.
