### ISSUE TITLE
Decide what to do with past CoP presentation materials

### ISSUE THREAD

**Issue by s-laugh** [esdc-devcop/esdc-devcop.github.io#62]
We need to decide on what to do with all the info currently stored on GCPedia for the past years presentation martial and videos.

Do we need to keep all, some, or none of it?
Where do we put it?

https://www.gcpedia.gc.ca/wiki/ESDC_Development_Community_-_Dev_CoP

**Comment by joel-ld** [comment]
Should we store the videos on a SDS Youtube channel ?  Or there is an issue with that ? :)

**Comment by s-laugh** [comment]
> 
> 
> Should we store the videos on a SDS Youtube channel ? Or there is an issue with that ? :)

That could be an option. Network speeds, and privacy issues would be the main constraints.
