### ISSUE TITLE
Topic: Series of pipeline sessions based of different categories

### ISSUE THREAD

**Issue by joel-ld** [esdc-devcop/esdc-devcop.github.io#86]
### Goals / Recommendation

Would be great if we create a series of small demo of a pipeline based on different categories.
Example : 
- Security analysis tools
- Code quality analysis (Roselyn, FxCop, etc)
- Performance analysis tools
- Accessibility analysis tools

To show these tool, we can build a sample project (ex : todo app) with some predefined examples of bad code)
And then doing live demo of theses.

### Community Expectations

Present the tools to show the benefit and how it changes your dev workflow.

### References

to do ...

**Comment by s-laugh** [comment]
Interesting idea, would this be better as one topic or multiple?

It does touch on other topic ideas #69 #7 #71 #85 #8

**Comment by joel-ld** [comment]
Yes exactly. 

Present the same Pipeline based on different category :)

**Comment by joel-ld** [comment]
The dummy project could be something like that : 
https://www.owasp.org/index.php/Category:OWASP_WebGoat_Project

It's a project with many security issues built-in. 

In our case, would be more issues related to the pipeline category

**Comment by s-laugh** [comment]
This seems to be more focused on the pipeline as a tool, than running and validating specific tests (label updated)
