### ISSUE TITLE
Topic: Azure DevOps Server features overview

### ISSUE THREAD

**Issue by jeanbenoitrochon** [esdc-devcop/esdc-devcop.github.io#87]
### Goals / Recommendation

Go through some of the features available in Azure DevOps server (Git, pipelines, containers, integration with VSCode and VS Studio 2019, etc.)

Expecting to have 2 parts:
- Part 1 will be how to do what we did in TFS 2015 in ADO
- Part 2 will be exploring new ADO tools and features, like pipelines.

### Community Expectations

Azure DevOps Server is about to be used in ESDC, this session would be an overview of the features.

### References

<https://docs.microsoft.com/en-us/azure/devops/server/whats-new?view=azure-devops>

**Comment by s-laugh** [comment]
Marking as `can't do` as Azure DevOps Server (TFS 2019) is not yet available at ESDC (it is coming soon).

**Comment by s-laugh** [comment]
ADO is set to update our TFS 2015 instance on January 18th, so we currently plan to have SADE with our MS rep (Francis) do a presentation in February.
