### ISSUE TITLE
Topic: CDTS v1.0.0 - Going open source - CI/CD

### ISSUE THREAD

**Issue by shawnthompson** [esdc-devcop/esdc-devcop.github.io#93]
### Goals / Recommendation

Moving CDTS to open source node project under wet-boew organization. Changing CDTS to compile with NodeJS and using Travis to deploy to different environments.

### Community Expectations

Looking for contributors, suggestions on how to make this project CI/CD.

### References

[wet-boew/cdts-sgdc](https://github.com/wet-boew/cdts-sgdc) (Coming soon)

**Comment by s-laugh** [comment]
Just clarifying, this looks like you would like to have some kind of "Workshop" where a chuck of work can be done to meet the _Goals_?

**Comment by shawnthompson** [comment]
More like an info session / announcement that the project is open to contributors and how it works.

**Comment by s-laugh** [comment]
In that case I believe this would be a duplicate #84 as it will cover pretty much everything you're suggesting only with a twist of how the features are translated into the .NET and Java templates. The only thing it would lack is the notice of CDTS being open source, however if the project is actually open by the time of the presentation, that could easily be added in.
